spring.application.name=backend
server.port=8080

spring.main.banner-mode=off

logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.apache=ERROR
logging.level.org.mongodb=ERROR
